// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (order_id, listing_id, price_cents, quantity)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, listing_id, price_cents, quantity
`

type CreateItemParams struct {
	OrderID    pgtype.UUID
	ListingID  pgtype.UUID
	PriceCents int32
	Quantity   int32
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.OrderID,
		arg.ListingID,
		arg.PriceCents,
		arg.Quantity,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ListingID,
		&i.PriceCents,
		&i.Quantity,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders(customer_id, email, total_price_cents, status)
VALUES ($1, $2, $3,  'pending')
RETURNING id, customer_id, created_at, total_price_cents, status, email
`

type CreateOrderParams struct {
	CustomerID      string
	Email           string
	TotalPriceCents int32
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.CustomerID, arg.Email, arg.TotalPriceCents)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CreatedAt,
		&i.TotalPriceCents,
		&i.Status,
		&i.Email,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, customer_id, created_at, total_price_cents, status, email FROM orders
WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CreatedAt,
		&i.TotalPriceCents,
		&i.Status,
		&i.Email,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT id, order_id, listing_id, price_cents, quantity FROM items WHERE order_id = $1
`

func (q *Queries) GetOrderItems(ctx context.Context, orderID pgtype.UUID) ([]Item, error) {
	rows, err := q.db.Query(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ListingID,
			&i.PriceCents,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2
WHERE id = $1
RETURNING id, customer_id, created_at, total_price_cents, status, email
`

type UpdateOrderStatusParams struct {
	ID     pgtype.UUID
	Status NullOrderStatus
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CreatedAt,
		&i.TotalPriceCents,
		&i.Status,
		&i.Email,
	)
	return i, err
}
